###
GET https://localhost:5002/api/Products
tenant: dbo

###
GET https://localhost:5002/api/Products
tenant: java


###
GET https://localhost:5002/api/Products
tenant: charlie

###
POST https://localhost:5002/api/Products
content-type: application/json
tenant: java

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}