###
GET https://localhost:5002/api/Products?id=1
tenant: java

###
GET https://localhost:5002/api/Products?id=1
tenant: charlie

###
GET https://localhost:5002/api/Products?id=1
tenant: dbo

###
POST https://localhost:5002/api/Products?id=1
content-type: application/json
tenant: java

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}